"""add indexes

Revision ID: ba2b9f19318c
Revises: e91a1d50404e
Create Date: 2025-08-22 23:07:21.240703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2b9f19318c'
down_revision = 'e91a1d50404e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_like_user_post', ['user_id', 'post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_like_user_post', type_='unique')

    # ### end Alembic commands ###
