services:
  web:
    build: ./app
    command: ["./wait-for-it.sh", "pg:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      DB_NAME: nc_tutorials_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: pg
      DB_PORT: 5432
    depends_on:
      - pg

  pg:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nc_tutorials_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/misc/django_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql


  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5433:80"
    depends_on:
      - pg

volumes:
  pgdata:
