version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workshop1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "5433:5433"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5433:80"
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
